import uuid
from datetime import datetime

from sqlmodel import Session, select

from app.core.db.models import AuditLog, User, UserRole
from app.core.db.session import create_engine_for_url, init_schema


def test_user_role_enum_values():
    assert {r.value for r in UserRole} == {"admin", "agent", "member"}


def test_user_table_metadata():
    assert User.__tablename__ == "user"
    assert "email" in User.model_fields
    assert "password_hash" in User.model_fields
    assert "role" in User.model_fields


def test_user_id_is_uuid_pk():
    """User.id is a UUID auto-generated by default_factory."""
    user = User(
        email="x@y.z",
        display_name="X",
        role=UserRole.admin,
        password_hash="hash",
    )
    assert isinstance(user.id, uuid.UUID)


def test_audit_log_defaults_now():
    log = AuditLog(action="test", entity_type="test")
    assert isinstance(log.at, datetime)


def test_engine_can_create_schema(tmp_path):
    db_path = tmp_path / "test.db"
    engine = create_engine_for_url(f"sqlite:///{db_path}")
    init_schema(engine)
    with Session(engine) as session:
        result = session.exec(select(User)).all()
        assert result == []
