/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SpoolsIndexRouteImport } from './routes/spools/index'
import { Route as RequestsIndexRouteImport } from './routes/requests/index'
import { Route as QueueIndexRouteImport } from './routes/queue/index'
import { Route as PrinterIndexRouteImport } from './routes/printer/index'
import { Route as CatalogIndexRouteImport } from './routes/catalog/index'
import { Route as SettingsSessionsRouteImport } from './routes/settings/sessions'
import { Route as Settings2faRouteImport } from './routes/settings/2fa'
import { Route as DevComponentsRouteImport } from './routes/dev/components'
import { Route as CatalogIdRouteImport } from './routes/catalog/$id'
import { Route as AdminUsersRouteImport } from './routes/admin/users'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpoolsIndexRoute = SpoolsIndexRouteImport.update({
  id: '/spools/',
  path: '/spools/',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsIndexRoute = RequestsIndexRouteImport.update({
  id: '/requests/',
  path: '/requests/',
  getParentRoute: () => rootRouteImport,
} as any)
const QueueIndexRoute = QueueIndexRouteImport.update({
  id: '/queue/',
  path: '/queue/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrinterIndexRoute = PrinterIndexRouteImport.update({
  id: '/printer/',
  path: '/printer/',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogIndexRoute = CatalogIndexRouteImport.update({
  id: '/catalog/',
  path: '/catalog/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSessionsRoute = SettingsSessionsRouteImport.update({
  id: '/settings/sessions',
  path: '/settings/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const Settings2faRoute = Settings2faRouteImport.update({
  id: '/settings/2fa',
  path: '/settings/2fa',
  getParentRoute: () => rootRouteImport,
} as any)
const DevComponentsRoute = DevComponentsRouteImport.update({
  id: '/dev/components',
  path: '/dev/components',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogIdRoute = CatalogIdRouteImport.update({
  id: '/catalog/$id',
  path: '/catalog/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/users': typeof AdminUsersRoute
  '/catalog/$id': typeof CatalogIdRoute
  '/dev/components': typeof DevComponentsRoute
  '/settings/2fa': typeof Settings2faRoute
  '/settings/sessions': typeof SettingsSessionsRoute
  '/catalog/': typeof CatalogIndexRoute
  '/printer/': typeof PrinterIndexRoute
  '/queue/': typeof QueueIndexRoute
  '/requests/': typeof RequestsIndexRoute
  '/spools/': typeof SpoolsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/users': typeof AdminUsersRoute
  '/catalog/$id': typeof CatalogIdRoute
  '/dev/components': typeof DevComponentsRoute
  '/settings/2fa': typeof Settings2faRoute
  '/settings/sessions': typeof SettingsSessionsRoute
  '/catalog': typeof CatalogIndexRoute
  '/printer': typeof PrinterIndexRoute
  '/queue': typeof QueueIndexRoute
  '/requests': typeof RequestsIndexRoute
  '/spools': typeof SpoolsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/admin/users': typeof AdminUsersRoute
  '/catalog/$id': typeof CatalogIdRoute
  '/dev/components': typeof DevComponentsRoute
  '/settings/2fa': typeof Settings2faRoute
  '/settings/sessions': typeof SettingsSessionsRoute
  '/catalog/': typeof CatalogIndexRoute
  '/printer/': typeof PrinterIndexRoute
  '/queue/': typeof QueueIndexRoute
  '/requests/': typeof RequestsIndexRoute
  '/spools/': typeof SpoolsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/admin/users'
    | '/catalog/$id'
    | '/dev/components'
    | '/settings/2fa'
    | '/settings/sessions'
    | '/catalog/'
    | '/printer/'
    | '/queue/'
    | '/requests/'
    | '/spools/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/admin/users'
    | '/catalog/$id'
    | '/dev/components'
    | '/settings/2fa'
    | '/settings/sessions'
    | '/catalog'
    | '/printer'
    | '/queue'
    | '/requests'
    | '/spools'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/register'
    | '/admin/users'
    | '/catalog/$id'
    | '/dev/components'
    | '/settings/2fa'
    | '/settings/sessions'
    | '/catalog/'
    | '/printer/'
    | '/queue/'
    | '/requests/'
    | '/spools/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  AdminUsersRoute: typeof AdminUsersRoute
  CatalogIdRoute: typeof CatalogIdRoute
  DevComponentsRoute: typeof DevComponentsRoute
  Settings2faRoute: typeof Settings2faRoute
  SettingsSessionsRoute: typeof SettingsSessionsRoute
  CatalogIndexRoute: typeof CatalogIndexRoute
  PrinterIndexRoute: typeof PrinterIndexRoute
  QueueIndexRoute: typeof QueueIndexRoute
  RequestsIndexRoute: typeof RequestsIndexRoute
  SpoolsIndexRoute: typeof SpoolsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spools/': {
      id: '/spools/'
      path: '/spools'
      fullPath: '/spools/'
      preLoaderRoute: typeof SpoolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests/': {
      id: '/requests/'
      path: '/requests'
      fullPath: '/requests/'
      preLoaderRoute: typeof RequestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queue/': {
      id: '/queue/'
      path: '/queue'
      fullPath: '/queue/'
      preLoaderRoute: typeof QueueIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/printer/': {
      id: '/printer/'
      path: '/printer'
      fullPath: '/printer/'
      preLoaderRoute: typeof PrinterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog/': {
      id: '/catalog/'
      path: '/catalog'
      fullPath: '/catalog/'
      preLoaderRoute: typeof CatalogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/sessions': {
      id: '/settings/sessions'
      path: '/settings/sessions'
      fullPath: '/settings/sessions'
      preLoaderRoute: typeof SettingsSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/2fa': {
      id: '/settings/2fa'
      path: '/settings/2fa'
      fullPath: '/settings/2fa'
      preLoaderRoute: typeof Settings2faRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/components': {
      id: '/dev/components'
      path: '/dev/components'
      fullPath: '/dev/components'
      preLoaderRoute: typeof DevComponentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog/$id': {
      id: '/catalog/$id'
      path: '/catalog/$id'
      fullPath: '/catalog/$id'
      preLoaderRoute: typeof CatalogIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  AdminUsersRoute: AdminUsersRoute,
  CatalogIdRoute: CatalogIdRoute,
  DevComponentsRoute: DevComponentsRoute,
  Settings2faRoute: Settings2faRoute,
  SettingsSessionsRoute: SettingsSessionsRoute,
  CatalogIndexRoute: CatalogIndexRoute,
  PrinterIndexRoute: PrinterIndexRoute,
  QueueIndexRoute: QueueIndexRoute,
  RequestsIndexRoute: RequestsIndexRoute,
  SpoolsIndexRoute: SpoolsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
