/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SpoolsIndexRouteImport } from './routes/spools/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as RequestsIndexRouteImport } from './routes/requests/index'
import { Route as QueueIndexRouteImport } from './routes/queue/index'
import { Route as PrinterIndexRouteImport } from './routes/printer/index'
import { Route as EstimatesIndexRouteImport } from './routes/estimates/index'
import { Route as CatalogIndexRouteImport } from './routes/catalog/index'
import { Route as ShareTokenRouteImport } from './routes/share/$token'
import { Route as SettingsShareLinksRouteImport } from './routes/settings/share-links'
import { Route as SettingsSessionsRouteImport } from './routes/settings/sessions'
import { Route as SettingsProfileRouteImport } from './routes/settings/profile'
import { Route as Settings2faRouteImport } from './routes/settings/2fa'
import { Route as DevComponentsRouteImport } from './routes/dev/components'
import { Route as CatalogIdRouteImport } from './routes/catalog/$id'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminProfilesRouteImport } from './routes/admin/profiles'
import { Route as AdminProfileLibraryRouteImport } from './routes/admin/profile-library'
import { Route as AdminInvitesRouteImport } from './routes/admin/invites'
import { Route as AdminModelsNewRouteImport } from './routes/admin/models/new'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpoolsIndexRoute = SpoolsIndexRouteImport.update({
  id: '/spools/',
  path: '/spools/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsIndexRoute = RequestsIndexRouteImport.update({
  id: '/requests/',
  path: '/requests/',
  getParentRoute: () => rootRouteImport,
} as any)
const QueueIndexRoute = QueueIndexRouteImport.update({
  id: '/queue/',
  path: '/queue/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrinterIndexRoute = PrinterIndexRouteImport.update({
  id: '/printer/',
  path: '/printer/',
  getParentRoute: () => rootRouteImport,
} as any)
const EstimatesIndexRoute = EstimatesIndexRouteImport.update({
  id: '/estimates/',
  path: '/estimates/',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogIndexRoute = CatalogIndexRouteImport.update({
  id: '/catalog/',
  path: '/catalog/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareTokenRoute = ShareTokenRouteImport.update({
  id: '/share/$token',
  path: '/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsShareLinksRoute = SettingsShareLinksRouteImport.update({
  id: '/settings/share-links',
  path: '/settings/share-links',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSessionsRoute = SettingsSessionsRouteImport.update({
  id: '/settings/sessions',
  path: '/settings/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/settings/profile',
  path: '/settings/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const Settings2faRoute = Settings2faRouteImport.update({
  id: '/settings/2fa',
  path: '/settings/2fa',
  getParentRoute: () => rootRouteImport,
} as any)
const DevComponentsRoute = DevComponentsRouteImport.update({
  id: '/dev/components',
  path: '/dev/components',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogIdRoute = CatalogIdRouteImport.update({
  id: '/catalog/$id',
  path: '/catalog/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProfilesRoute = AdminProfilesRouteImport.update({
  id: '/admin/profiles',
  path: '/admin/profiles',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProfileLibraryRoute = AdminProfileLibraryRouteImport.update({
  id: '/admin/profile-library',
  path: '/admin/profile-library',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInvitesRoute = AdminInvitesRouteImport.update({
  id: '/admin/invites',
  path: '/admin/invites',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminModelsNewRoute = AdminModelsNewRouteImport.update({
  id: '/admin/models/new',
  path: '/admin/models/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/invites': typeof AdminInvitesRoute
  '/admin/profile-library': typeof AdminProfileLibraryRoute
  '/admin/profiles': typeof AdminProfilesRoute
  '/admin/users': typeof AdminUsersRoute
  '/catalog/$id': typeof CatalogIdRoute
  '/dev/components': typeof DevComponentsRoute
  '/settings/2fa': typeof Settings2faRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/sessions': typeof SettingsSessionsRoute
  '/settings/share-links': typeof SettingsShareLinksRoute
  '/share/$token': typeof ShareTokenRoute
  '/catalog/': typeof CatalogIndexRoute
  '/estimates/': typeof EstimatesIndexRoute
  '/printer/': typeof PrinterIndexRoute
  '/queue/': typeof QueueIndexRoute
  '/requests/': typeof RequestsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/spools/': typeof SpoolsIndexRoute
  '/admin/models/new': typeof AdminModelsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/invites': typeof AdminInvitesRoute
  '/admin/profile-library': typeof AdminProfileLibraryRoute
  '/admin/profiles': typeof AdminProfilesRoute
  '/admin/users': typeof AdminUsersRoute
  '/catalog/$id': typeof CatalogIdRoute
  '/dev/components': typeof DevComponentsRoute
  '/settings/2fa': typeof Settings2faRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/sessions': typeof SettingsSessionsRoute
  '/settings/share-links': typeof SettingsShareLinksRoute
  '/share/$token': typeof ShareTokenRoute
  '/catalog': typeof CatalogIndexRoute
  '/estimates': typeof EstimatesIndexRoute
  '/printer': typeof PrinterIndexRoute
  '/queue': typeof QueueIndexRoute
  '/requests': typeof RequestsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/spools': typeof SpoolsIndexRoute
  '/admin/models/new': typeof AdminModelsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/invites': typeof AdminInvitesRoute
  '/admin/profile-library': typeof AdminProfileLibraryRoute
  '/admin/profiles': typeof AdminProfilesRoute
  '/admin/users': typeof AdminUsersRoute
  '/catalog/$id': typeof CatalogIdRoute
  '/dev/components': typeof DevComponentsRoute
  '/settings/2fa': typeof Settings2faRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/sessions': typeof SettingsSessionsRoute
  '/settings/share-links': typeof SettingsShareLinksRoute
  '/share/$token': typeof ShareTokenRoute
  '/catalog/': typeof CatalogIndexRoute
  '/estimates/': typeof EstimatesIndexRoute
  '/printer/': typeof PrinterIndexRoute
  '/queue/': typeof QueueIndexRoute
  '/requests/': typeof RequestsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/spools/': typeof SpoolsIndexRoute
  '/admin/models/new': typeof AdminModelsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/admin/invites'
    | '/admin/profile-library'
    | '/admin/profiles'
    | '/admin/users'
    | '/catalog/$id'
    | '/dev/components'
    | '/settings/2fa'
    | '/settings/profile'
    | '/settings/sessions'
    | '/settings/share-links'
    | '/share/$token'
    | '/catalog/'
    | '/estimates/'
    | '/printer/'
    | '/queue/'
    | '/requests/'
    | '/settings/'
    | '/spools/'
    | '/admin/models/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/admin/invites'
    | '/admin/profile-library'
    | '/admin/profiles'
    | '/admin/users'
    | '/catalog/$id'
    | '/dev/components'
    | '/settings/2fa'
    | '/settings/profile'
    | '/settings/sessions'
    | '/settings/share-links'
    | '/share/$token'
    | '/catalog'
    | '/estimates'
    | '/printer'
    | '/queue'
    | '/requests'
    | '/settings'
    | '/spools'
    | '/admin/models/new'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/admin/invites'
    | '/admin/profile-library'
    | '/admin/profiles'
    | '/admin/users'
    | '/catalog/$id'
    | '/dev/components'
    | '/settings/2fa'
    | '/settings/profile'
    | '/settings/sessions'
    | '/settings/share-links'
    | '/share/$token'
    | '/catalog/'
    | '/estimates/'
    | '/printer/'
    | '/queue/'
    | '/requests/'
    | '/settings/'
    | '/spools/'
    | '/admin/models/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  AdminInvitesRoute: typeof AdminInvitesRoute
  AdminProfileLibraryRoute: typeof AdminProfileLibraryRoute
  AdminProfilesRoute: typeof AdminProfilesRoute
  AdminUsersRoute: typeof AdminUsersRoute
  CatalogIdRoute: typeof CatalogIdRoute
  DevComponentsRoute: typeof DevComponentsRoute
  Settings2faRoute: typeof Settings2faRoute
  SettingsProfileRoute: typeof SettingsProfileRoute
  SettingsSessionsRoute: typeof SettingsSessionsRoute
  SettingsShareLinksRoute: typeof SettingsShareLinksRoute
  ShareTokenRoute: typeof ShareTokenRoute
  CatalogIndexRoute: typeof CatalogIndexRoute
  EstimatesIndexRoute: typeof EstimatesIndexRoute
  PrinterIndexRoute: typeof PrinterIndexRoute
  QueueIndexRoute: typeof QueueIndexRoute
  RequestsIndexRoute: typeof RequestsIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  SpoolsIndexRoute: typeof SpoolsIndexRoute
  AdminModelsNewRoute: typeof AdminModelsNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spools/': {
      id: '/spools/'
      path: '/spools'
      fullPath: '/spools/'
      preLoaderRoute: typeof SpoolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests/': {
      id: '/requests/'
      path: '/requests'
      fullPath: '/requests/'
      preLoaderRoute: typeof RequestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queue/': {
      id: '/queue/'
      path: '/queue'
      fullPath: '/queue/'
      preLoaderRoute: typeof QueueIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/printer/': {
      id: '/printer/'
      path: '/printer'
      fullPath: '/printer/'
      preLoaderRoute: typeof PrinterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estimates/': {
      id: '/estimates/'
      path: '/estimates'
      fullPath: '/estimates/'
      preLoaderRoute: typeof EstimatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog/': {
      id: '/catalog/'
      path: '/catalog'
      fullPath: '/catalog/'
      preLoaderRoute: typeof CatalogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$token': {
      id: '/share/$token'
      path: '/share/$token'
      fullPath: '/share/$token'
      preLoaderRoute: typeof ShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/share-links': {
      id: '/settings/share-links'
      path: '/settings/share-links'
      fullPath: '/settings/share-links'
      preLoaderRoute: typeof SettingsShareLinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/sessions': {
      id: '/settings/sessions'
      path: '/settings/sessions'
      fullPath: '/settings/sessions'
      preLoaderRoute: typeof SettingsSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/settings/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/2fa': {
      id: '/settings/2fa'
      path: '/settings/2fa'
      fullPath: '/settings/2fa'
      preLoaderRoute: typeof Settings2faRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/components': {
      id: '/dev/components'
      path: '/dev/components'
      fullPath: '/dev/components'
      preLoaderRoute: typeof DevComponentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog/$id': {
      id: '/catalog/$id'
      path: '/catalog/$id'
      fullPath: '/catalog/$id'
      preLoaderRoute: typeof CatalogIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/profiles': {
      id: '/admin/profiles'
      path: '/admin/profiles'
      fullPath: '/admin/profiles'
      preLoaderRoute: typeof AdminProfilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/profile-library': {
      id: '/admin/profile-library'
      path: '/admin/profile-library'
      fullPath: '/admin/profile-library'
      preLoaderRoute: typeof AdminProfileLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/invites': {
      id: '/admin/invites'
      path: '/admin/invites'
      fullPath: '/admin/invites'
      preLoaderRoute: typeof AdminInvitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/models/new': {
      id: '/admin/models/new'
      path: '/admin/models/new'
      fullPath: '/admin/models/new'
      preLoaderRoute: typeof AdminModelsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  AdminInvitesRoute: AdminInvitesRoute,
  AdminProfileLibraryRoute: AdminProfileLibraryRoute,
  AdminProfilesRoute: AdminProfilesRoute,
  AdminUsersRoute: AdminUsersRoute,
  CatalogIdRoute: CatalogIdRoute,
  DevComponentsRoute: DevComponentsRoute,
  Settings2faRoute: Settings2faRoute,
  SettingsProfileRoute: SettingsProfileRoute,
  SettingsSessionsRoute: SettingsSessionsRoute,
  SettingsShareLinksRoute: SettingsShareLinksRoute,
  ShareTokenRoute: ShareTokenRoute,
  CatalogIndexRoute: CatalogIndexRoute,
  EstimatesIndexRoute: EstimatesIndexRoute,
  PrinterIndexRoute: PrinterIndexRoute,
  QueueIndexRoute: QueueIndexRoute,
  RequestsIndexRoute: RequestsIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  SpoolsIndexRoute: SpoolsIndexRoute,
  AdminModelsNewRoute: AdminModelsNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
