/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SpoolsIndexRouteImport } from './routes/spools/index'
import { Route as RequestsIndexRouteImport } from './routes/requests/index'
import { Route as QueueIndexRouteImport } from './routes/queue/index'
import { Route as PrinterIndexRouteImport } from './routes/printer/index'
import { Route as CatalogIndexRouteImport } from './routes/catalog/index'
import { Route as ShareTokenRouteImport } from './routes/share/$token'
import { Route as DevComponentsRouteImport } from './routes/dev/components'
import { Route as CatalogIdRouteImport } from './routes/catalog/$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpoolsIndexRoute = SpoolsIndexRouteImport.update({
  id: '/spools/',
  path: '/spools/',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsIndexRoute = RequestsIndexRouteImport.update({
  id: '/requests/',
  path: '/requests/',
  getParentRoute: () => rootRouteImport,
} as any)
const QueueIndexRoute = QueueIndexRouteImport.update({
  id: '/queue/',
  path: '/queue/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrinterIndexRoute = PrinterIndexRouteImport.update({
  id: '/printer/',
  path: '/printer/',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogIndexRoute = CatalogIndexRouteImport.update({
  id: '/catalog/',
  path: '/catalog/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareTokenRoute = ShareTokenRouteImport.update({
  id: '/share/$token',
  path: '/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const DevComponentsRoute = DevComponentsRouteImport.update({
  id: '/dev/components',
  path: '/dev/components',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogIdRoute = CatalogIdRouteImport.update({
  id: '/catalog/$id',
  path: '/catalog/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/catalog/$id': typeof CatalogIdRoute
  '/dev/components': typeof DevComponentsRoute
  '/share/$token': typeof ShareTokenRoute
  '/catalog/': typeof CatalogIndexRoute
  '/printer/': typeof PrinterIndexRoute
  '/queue/': typeof QueueIndexRoute
  '/requests/': typeof RequestsIndexRoute
  '/spools/': typeof SpoolsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/catalog/$id': typeof CatalogIdRoute
  '/dev/components': typeof DevComponentsRoute
  '/share/$token': typeof ShareTokenRoute
  '/catalog': typeof CatalogIndexRoute
  '/printer': typeof PrinterIndexRoute
  '/queue': typeof QueueIndexRoute
  '/requests': typeof RequestsIndexRoute
  '/spools': typeof SpoolsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/catalog/$id': typeof CatalogIdRoute
  '/dev/components': typeof DevComponentsRoute
  '/share/$token': typeof ShareTokenRoute
  '/catalog/': typeof CatalogIndexRoute
  '/printer/': typeof PrinterIndexRoute
  '/queue/': typeof QueueIndexRoute
  '/requests/': typeof RequestsIndexRoute
  '/spools/': typeof SpoolsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/catalog/$id'
    | '/dev/components'
    | '/share/$token'
    | '/catalog/'
    | '/printer/'
    | '/queue/'
    | '/requests/'
    | '/spools/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/catalog/$id'
    | '/dev/components'
    | '/share/$token'
    | '/catalog'
    | '/printer'
    | '/queue'
    | '/requests'
    | '/spools'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/catalog/$id'
    | '/dev/components'
    | '/share/$token'
    | '/catalog/'
    | '/printer/'
    | '/queue/'
    | '/requests/'
    | '/spools/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  CatalogIdRoute: typeof CatalogIdRoute
  DevComponentsRoute: typeof DevComponentsRoute
  ShareTokenRoute: typeof ShareTokenRoute
  CatalogIndexRoute: typeof CatalogIndexRoute
  PrinterIndexRoute: typeof PrinterIndexRoute
  QueueIndexRoute: typeof QueueIndexRoute
  RequestsIndexRoute: typeof RequestsIndexRoute
  SpoolsIndexRoute: typeof SpoolsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spools/': {
      id: '/spools/'
      path: '/spools'
      fullPath: '/spools/'
      preLoaderRoute: typeof SpoolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests/': {
      id: '/requests/'
      path: '/requests'
      fullPath: '/requests/'
      preLoaderRoute: typeof RequestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queue/': {
      id: '/queue/'
      path: '/queue'
      fullPath: '/queue/'
      preLoaderRoute: typeof QueueIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/printer/': {
      id: '/printer/'
      path: '/printer'
      fullPath: '/printer/'
      preLoaderRoute: typeof PrinterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog/': {
      id: '/catalog/'
      path: '/catalog'
      fullPath: '/catalog/'
      preLoaderRoute: typeof CatalogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$token': {
      id: '/share/$token'
      path: '/share/$token'
      fullPath: '/share/$token'
      preLoaderRoute: typeof ShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/components': {
      id: '/dev/components'
      path: '/dev/components'
      fullPath: '/dev/components'
      preLoaderRoute: typeof DevComponentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog/$id': {
      id: '/catalog/$id'
      path: '/catalog/$id'
      fullPath: '/catalog/$id'
      preLoaderRoute: typeof CatalogIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  CatalogIdRoute: CatalogIdRoute,
  DevComponentsRoute: DevComponentsRoute,
  ShareTokenRoute: ShareTokenRoute,
  CatalogIndexRoute: CatalogIndexRoute,
  PrinterIndexRoute: PrinterIndexRoute,
  QueueIndexRoute: QueueIndexRoute,
  RequestsIndexRoute: RequestsIndexRoute,
  SpoolsIndexRoute: SpoolsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
