; HEADER_BLOCK_START
; generated by OrcaSlicer 2.3.2 (SYNTHETIC fixture — missing the required print-time line)
G90
M83
M107
; CONFIG_BLOCK_START
; filament used [mm] = 25735.79
; filament used [cm3] = 61.90
; filament used [g] = 76.76
; total filament cost = 4.60
; filament_settings_id = "AI Rosa3D PLA Starter"
; printer_settings_id = "Creality K1 Max (0.4 nozzle)"
; print_settings_id = "AI 0.20mm (0.4 nozzle) - MicroSwiss HF"
; CONFIG_BLOCK_END
