; HEADER_BLOCK_START
; generated by OrcaSlicer 2.3.2 on 2026-06-04 (SYNTHETIC fixture — NOT a retained slice)
G90
M83
M104 S210
G1 Z0.2 F600
; ... print body elided ...
M107
; CONFIG_BLOCK_START
; estimated printing time (normal mode) = 2m 35s
; estimated printing time (silent mode) = 3m 02s
; filament used [mm] = 412.83
; filament used [cm3] = 0.99
; filament used [g] = 1.23
; total filament cost = 0.07
; filament_settings_id = "AI Rosa3D PLA Starter"
; printer_settings_id = "Creality K1 Max (0.4 nozzle)"
; print_settings_id = "AI 0.20mm (0.4 nozzle) - MicroSwiss HF"
; CONFIG_BLOCK_END
