; HEADER_BLOCK_START
; generated by OrcaSlicer 2.3.2 on 2026-06-01 (SYNTHETIC fixture — NOT a retained slice)
G90
M83
M104 S210
G1 Z0.2 F600
G1 X10 Y10 E1.0 F1800
G1 X20 Y10 E2.0
; ... print body elided ...
M107
; CONFIG_BLOCK_START
; estimated printing time (normal mode) = 3h35m47s
; estimated printing time (silent mode) = 3h58m12s
; filament used [mm] = 25735.79
; filament used [cm3] = 61.90
; filament used [g] = 76.76
; total filament cost = 4.60
; filament_settings_id = "AI Rosa3D PLA Starter"
; printer_settings_id = "Creality K1 Max (0.4 nozzle)"
; print_settings_id = "AI 0.20mm (0.4 nozzle) - MicroSwiss HF"
; CONFIG_BLOCK_END
