; HEADER_BLOCK_START
; generated by OrcaSlicer 2.3.2 on 2026-06-01 (SYNTHETIC fixture — NOT a retained slice)
G90
M83
M104 S230
G1 Z0.2 F600
G1 X10 Y10 E1.0 F1200
M107
; CONFIG_BLOCK_START
; estimated printing time (normal mode) = 8h06m05s
; estimated printing time (silent mode) = 8h44m31s
; filament used [mm] = 25901.34
; filament used [cm3] = 62.41
; filament used [g] = 77.25
; total filament cost = 5.02
; filament_settings_id = "AI Rosa3D Flex 96A Black"
; printer_settings_id = "Creality K1 Max (0.4 nozzle)"
; print_settings_id = "AI 0.20mm TPU - FlowTech"
; CONFIG_BLOCK_END
