"""apps/api/app/core/db/models/_auth.py"""

import datetime
import uuid

from sqlalchemy import Column, Index, text
from sqlmodel import Field, SQLModel

from ._helpers import UTCDateTime, uuid_fk


class RefreshToken(SQLModel, table=True):
    __tablename__ = "refresh_tokens"
    __table_args__ = (
        # Match migration 0009's explicit index names. Without these,
        # SQLModel's column-level ``index=True`` autogenerate produces
        # ``ix_refresh_tokens_family_id``, drifting from the migration's
        # ``ix_refresh_tokens_family``. Keeping them in sync silences
        # ``alembic check`` (TB-016 / DOC-DRIFT-2 Drift 5).
        Index(
            "ix_refresh_tokens_user_active",
            "user_id",
            sqlite_where=text("revoked_at IS NULL"),
        ),
        Index(
            "ix_refresh_tokens_family",
            "family_id",
        ),
        # Partial unique index: at most one active (non-revoked) token per family.
        # Prevents concurrent rotations from inserting two active rows for the same family.
        # The sqlite_where clause makes this a partial index on SQLite; on PostgreSQL
        # add postgresql_where=text("revoked_at IS NULL") when migrating.
        Index(
            "ux_refresh_tokens_family_active",
            "family_id",
            unique=True,
            sqlite_where=text("revoked_at IS NULL"),
        ),
    )

    id: uuid.UUID = Field(default_factory=uuid.uuid4, primary_key=True)
    user_id: uuid.UUID = Field(
        sa_column=uuid_fk("user.id", ondelete="CASCADE", nullable=False),
    )
    # Index moved to __table_args__ (Story 18.5 / Drift 5 close-out) so the
    # SQLModel-autogenerated name does not drift from migration 0009.
    family_id: uuid.UUID = Field()
    family_issued_at: datetime.datetime = Field(sa_column=Column(UTCDateTime, nullable=False))
    token_hash: str = Field(unique=True)
    issued_at: datetime.datetime = Field(sa_column=Column(UTCDateTime, nullable=False))
    expires_at: datetime.datetime = Field(sa_column=Column(UTCDateTime, nullable=False))
    replaced_at: datetime.datetime | None = Field(
        default=None, sa_column=Column(UTCDateTime, nullable=True)
    )
    replaced_by_id: uuid.UUID | None = Field(
        default=None,
        sa_column=uuid_fk("refresh_tokens.id", ondelete="SET NULL", nullable=True),
    )
    revoked_at: datetime.datetime | None = Field(
        default=None, sa_column=Column(UTCDateTime, nullable=True)
    )
    revoke_reason: str | None = None
    last_used_at: datetime.datetime | None = Field(
        default=None, sa_column=Column(UTCDateTime, nullable=True)
    )
    ip: str | None = None
    user_agent: str | None = None
