#!/usr/bin/env bash
# Regenerate the gitignored derived inputs the design-sync converter reads, so a
# fresh checkout is reproducible without hand-editing config. Produces:
#   .design-sync/.cache/ds-entry.tsx  — barrel re-exporting every non-test
#                                       src/ui component + forcing the pl locale
#                                       (cfg.entry points here)
#   .design-sync/.cache/app.css       — the app's compiled Tailwind CSS
#                                       (cfg.cssEntry points here; the dist file
#                                       name is content-hashed, so resolve the
#                                       newest each run instead of pinning a hash)
#
# Run from anywhere, AFTER the app has been built (`npm run build` in apps/web,
# which emits dist/assets/index-<hash>.css).
set -euo pipefail
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"   # apps/web
cd "$HERE"
mkdir -p .design-sync/.cache

# 1. Barrel entry (component set + global i18n init, Polish).
{
  echo "// AUTO-GENERATED by .design-sync/prepare.sh — do not edit."
  echo "// Paths relative to .design-sync/.cache/."
  echo 'import i18n from "../../src/locales/i18n";  // side-effect: global react-i18next instance'
  echo 'void i18n.changeLanguage("pl");  // previews render in Polish (brand default)'
  for f in $(ls src/ui/*.tsx src/ui/custom/*.tsx | grep -v '\.test\.' | sort); do
    echo "export * from \"../../$f\";"
  done
} > .design-sync/.cache/ds-entry.tsx

# 2. Compiled app CSS (newest content-hashed bundle from the Vite build).
CSS="$(ls -t dist/assets/index-*.css 2>/dev/null | head -1 || true)"
if [ -z "$CSS" ]; then
  echo "prepare: no dist/assets/index-*.css found — run 'npm run build' first" >&2
  exit 1
fi
cp "$CSS" .design-sync/.cache/app.css

echo "prepare: regenerated .cache/ds-entry.tsx and .cache/app.css (from $CSS)"
